---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: El panel bien arquitectado en la NetApp Console analiza las configuraciones del sistema para fiabilidad, seguridad, excelencia operativa, optimización de costes y eficiencia del rendimiento, proporcionando información y recomendaciones para ayudarte a lograr la excelencia operativa. 
---
= Descubre el panel bien arquitectado en la consola de NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
El panel de control de arquitectura óptima en NetApp Console te ayuda a mantener y operar configuraciones fiables, seguras, eficientes y rentables que se alinean con los marcos de arquitectura óptima para el tipo de almacenamiento que usas. El panel de control proporciona una vista unificada de todas las cuentas y regiones, ayuda a los equipos a identificar y priorizar riesgos, y admite reglas personalizadas para requisitos específicos. Los análisis diarios automáticos de las configuraciones de tu sistema de almacenamiento te ofrecen información detallada y recomendaciones para ayudarte a optimizar tus entornos de almacenamiento.



[[how-it-works]]
== Cómo funciona

El panel de control «Well-Architected» analiza tus configuraciones a diario. El análisis ofrece el estado de «Well-Architected», información detallada y recomendaciones.

Una vez finalizado el análisis diario, las configuraciones aparecen como "optimizadas" o "no optimizadas" en el panel de control de well-architected. Encontrarás la puntuación total de optimización, los problemas de configuración por categoría y una lista de problemas de configuración y recomendaciones. Puedes revisar las recomendaciones para los problemas de configuración. Algunos problemas pueden solucionarse automáticamente desde el panel de control de well-architected, mientras que otros requieren intervención manual. En este caso, el panel de control de well-architected te da instrucciones detalladas para ayudarte a implementar los cambios recomendados.

Puedes descartar el análisis de las configuraciones que no se aplican a tus entornos. Así evitas alertas innecesarias y resultados de optimización inexactos. Cuando descartas el análisis de una configuración específica, el panel de control well-architected no incluye esa configuración en la puntuación total de optimización.



[[why-it-matters]]
== Por qué es importante

El panel de control bien diseñado en NetApp Console aplica las mejores prácticas a entornos de almacenamiento, bases de datos y VMware a gran escala, combinando una evaluación continua con recomendaciones y acciones de remediación. La remediación automatizada aplicada en el panel de control bien diseñado reduce los errores humanos, asegura una gestión uniforme y mantiene el rendimiento y la fiabilidad en todas tus infraestructuras de sistema.



[[supported-storage-systems]]
== Sistemas de almacenamiento compatibles

El panel bien arquitectado en la Consola admite los siguientes sistemas de almacenamiento:

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP en Microsoft Azure




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== Empieza a utilizar la NetApp Console para detectar y corregir errores de configuración del sistema

Para empezar a utilizar la NetApp Console, regístrate, añade tus credenciales y configura la conexión para gestionar tus recursos y optimizar las configuraciones del sistema.

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Flujo de trabajo para empezar con NetApp Console (aplicación SaaS)"^]



[[related-information]]
== Información relacionada

* link:fsx/improve-configurations-fsx.html["Implementa sistemas de archivos FSx para ONTAP bien diseñados"^]
* link:cvo/improve-configurations-cvo.html["Implementa sistemas Cloud Volumes ONTAP bien diseñados"^]

