---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: El panel bien arquitectado en la NetApp Console analiza las configuraciones del sistema para fiabilidad, seguridad, excelencia operativa, optimización de costes y eficiencia del rendimiento, proporcionando información y recomendaciones para ayudarte a lograr la excelencia operativa. 
---
= Descubre el panel bien arquitectado en la consola de NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory te ayuda a mantener y operar configuraciones fiables, seguras, eficientes y rentables que se alinean con los marcos bien arquitectados para el tipo de almacenamiento que usas. El panel bien arquitectado en NetApp Console ofrece una vista unificada entre cuentas y regiones, ayuda a los equipos a identificar y priorizar riesgos, y admite reglas personalizadas para requisitos específicos. Los análisis automáticos diarios de las configuraciones de tu sistema de almacenamiento proporcionan información y recomendaciones para ayudarte a optimizar tus entornos de almacenamiento.



[[how-it-works]]
== Cómo funciona

Workload Factory analiza tus configuraciones a diario. El análisis proporciona el estado bien arquitectado, información y recomendaciones para ayudarte a optimizar tus entornos de almacenamiento.

Una vez finalizado el análisis diario, las configuraciones aparecen como "optimizadas" o "no optimizadas" en el panel de control de well-architected. Encontrarás los problemas de configuración clasificados por categoría del marco well-architected (fiabilidad, seguridad, excelencia operativa, optimización de costes y eficiencia del rendimiento) y una lista de problemas de configuración y recomendaciones. Workload Factory puede solucionar algunos problemas automáticamente, mientras que otros requieren intervención manual. En este caso, la recomendación te da instrucciones detalladas para ayudarte a implementar los cambios.

Puedes descartar el análisis de las configuraciones que no se apliquen a tus entornos. Descartar configuraciones evita alertas innecesarias y resultados de optimización inexactos.



[[why-it-matters]]
== Por qué es importante

Workload Factory aplica las mejores prácticas a entornos de almacenamiento a gran escala, bases de datos y VMware, combinando una evaluación continua con recomendaciones y medidas correctivas. La corrección automatizada reduce los errores humanos, garantiza una gestión uniforme y preserva el rendimiento y la fiabilidad en todas las infraestructuras de tu sistema.



[[supported-storage-systems]]
== Sistemas de almacenamiento compatibles

El panel bien arquitectado en la Consola admite los siguientes sistemas de almacenamiento:

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP en Microsoft Azure




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== Empieza a utilizar la NetApp Console para detectar y corregir errores de configuración del sistema

Para empezar a utilizar la NetApp Console, regístrate, añade tus credenciales y configura la conexión para gestionar tus recursos y optimizar las configuraciones del sistema.

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Flujo de trabajo para empezar con NetApp Console (aplicación SaaS)"^]



[[related-information]]
== Información relacionada

* link:fsx/improve-configurations-fsx.html["Implementa sistemas de archivos FSx para ONTAP bien diseñados"^]
* link:cvo/improve-configurations-cvo.html["Implementa sistemas Cloud Volumes ONTAP bien diseñados"^]

