---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, well-architected, well-architected dashboard, amazon fsx for netapp ontap, fsx for ontap, cloud volumes ontap, microsoft azure' 
summary: Descubre las novedades del panel de control bien arquitectado en NetApp Console. 
---
= Novedades del panel de control well-architected en NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Descubre las novedades del panel de control bien arquitectado en NetApp Console.



[[17-august-2026]]
== 17 de agosto de 2026



[[fsx-for-ontap-support-in-the-well-architected-dashboard-in-netapp-console]]
=== Compatibilidad con FSx para ONTAP en el panel bien arquitectado en NetApp Console

El panel bien diseñado en la NetApp Console está disponible para Amazon FSx for NetApp ONTAP.

link:https://docs.netapp.com/us-en/console-well-architected/fsx/configuration-analysis-fsx.html["Infórmate sobre el análisis de configuración de FSx for ONTAP"]



[[updated-configuration-names-in-the-well-architected-dashboard]]
=== Nombres de configuración actualizados en el panel de control de well-architected

El panel bien diseñado en NetApp Console ahora incluye nuevos nombres de configuración de almacenamiento.

La siguiente tabla muestra los nombres de configuración antiguos y sus correspondientes nombres de configuración nuevos en el panel de control de well-architected.

[cols="1,1"]
|===
| Nombre de la configuración anterior | Nuevo nombre de configuración 


| Programar copias de seguridad de volúmenes | Copias de seguridad de volúmenes 


| Límite de capacidad del SSD | Margen de capacidad del SSD 


| Umbral de capacidad de archivos | Margen de capacidad de archivos 


| Fiabilidad de los datos de retención a largo plazo | Etiquetas de políticas de replicación 


| Instantáneas locales programadas | Política de SnapVault 


| Elimina las copias de seguridad innecesarias | Caducidad de la copia de seguridad 


| Eliminar instantáneas innecesarias | Caducidad de la instantánea 


| Capacidad no aprovechada del SSD | Capacidad de SSD sobredimensionada 


| Dispositivos de bloque inactivos | Dispositivos de bloque inactivos (LUN) 


| Optimiza el TCO trasladando los datos inactivos a niveles de almacenamiento | Jerarquización de datos inactivos 


| Informes sobre la capacidad lógica de los volúmenes | Informes de capacidad visibles para el host 


| FlexGroup volúmenes reequilibrados | Reequilibrar volúmenes FlexGroup 


| FlexVol reequilibrio de volúmenes | Reequilibra los volúmenes FlexVol 


| Modo de escritura de la relación de caché | FlexCache modo de escritura 


| Optimiza el tamaño del volumen de caché | FlexCache tamaño de la réplica 


| Acceso no autorizado al volumen | Acceso no autorizado a un volumen iSCSI 


| ARP/AI desactivado | Protección contra el ransomware (ARP/IA) 
|===


[[well-architected-issues-displayed-in-netapp-console-systems-page]]
=== Problemas de Well-Architected que se muestran en la página Systems de NetApp Console

Las notificaciones sobre problemas relacionados con el diseño óptimo están disponibles para Cloud Volumes ONTAP en Microsoft Azure desde la página Sistemas de gestión de almacenamiento en la NetApp Console. Esta función te ayuda a identificar rápidamente problemas de configuración en tus sistemas Cloud Volumes ONTAP en Azure y a navegar al panel de control well-architected de Workloads desde la notificación.



[[10-august-2026]]
== 10 de agosto de 2026



[[google-cloud-netapp-volumes-support-in-the-well-architected-dashboard]]
=== Compatibilidad de Google Cloud NetApp Volumes en el panel de control well-architected

El panel de control de la NetApp Console ahora es compatible con Google Cloud NetApp Volumes. Los administradores de almacenamiento pueden consultar el estado de sus grupos de almacenamiento y configuraciones, obtener recomendaciones para mejorar la eficiencia, el coste, el rendimiento, la fiabilidad y la seguridad, y tomar medidas para optimizar las operaciones y seguir las mejores prácticas.

Más información sobre link:https://docs.netapp.com/us-en/console-well-architected/gcnv/configuration-analysis-gcnv.html["Análisis de configuración para Google Cloud NetApp Volumes"].



[[03-august-2026]]
== 3 de agosto de 2026



[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== Corregir, descartar y reactivar configuraciones de Cloud Volumes ONTAP en Microsoft Azure

El panel bien estructurado en la NetApp Console ahora te permite corregir las recomendaciones de configuración para tus sistemas Cloud Volumes ONTAP.

También puedes excluir una o varias configuraciones del análisis de well-architected. Esto te permite ignorar configuraciones específicas que no se aplican a tu entorno.

Si deseas incluir más adelante una configuración que hayas descartado, puedes reactivarla en el panel de control de well-architected. Esto restaura la configuración en el análisis y te permite obtener recomendaciones y soluciones para ella.

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["Corregir, descartar y reactivar configuraciones de Cloud Volumes ONTAP en Microsoft Azure"]



[[20-july-2026]]
== 20 de julio de 2026



[[introducing-the-well-architected-dashboard-in-netapp-console]]
=== Presentamos el panel bien arquitectado en NetApp Console

El panel de control well-architected en NetApp Console ofrece una vista única de tus sistemas de almacenamiento y configuraciones en todas las cuentas y regiones. El panel de control proporciona información y recomendaciones para ayudarte a alcanzar la excelencia operativa. Puedes ver el estado well-architected de tus configuraciones, los problemas de configuración organizados según los pilares del marco well-architected para el tipo de almacenamiento que usas, y una lista de problemas de configuración y recomendaciones.

Obtén más información sobre el link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["panel bien diseñado"].

El panel bien arquitectado en la Consola está disponible para link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["Cloud Volumes ONTAP en Microsoft Azure."]



[[build-your-own-custom-rules]]
=== Crea tus propias reglas personalizadas

Redacta reglas personalizadas en lenguaje sencillo para asegurarte de que tus sistemas cumplan con las normas de tu organización y las mejores prácticas de NetApp. Prueba las reglas con una simulación y luego programa que se ejecuten en todos tus entornos.

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["Obtén más información sobre las reglas personalizadas"]
