---
sidebar: sidebar 
permalink: fsx/configuration-analysis-fsx.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: El panel de control bien diseñado analiza periódicamente las configuraciones del sistema de archivos FSx for ONTAP para determinar si hay algún problema de configuración. 
---
= Análisis de la configuración de Amazon FSx para NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El panel bien arquitectado en la NetApp Console analiza regularmente las configuraciones de los sistemas de almacenamiento para determinar si hay algún problema de configuración en tus sistemas de archivos Amazon FSx for NetApp ONTAP. Cuando se encuentran problemas, el panel te muestra cuáles son y te explica qué necesitas cambiar para asegurar que tus sistemas de almacenamiento logren el máximo rendimiento, eficiencia de costos y cumplimiento con las mejores prácticas.

Las capacidades clave incluyen:

* Análisis diario de configuración
* Validaciones automáticas de las mejores prácticas para los sistemas de almacenamiento NetApp ONTAP y los proveedores de almacenamiento asociados
* Observabilidad proactiva
* De la información a la acción


Directiva sin resolver en <stdin> - include::well-architected-workloads.adoc[]



[[analysis-requirements]]
== Requisitos de análisis

Para realizar un análisis completo del sistema de archivos, debes hacer lo siguiente:

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["Implementa un agente de NetApp Console"^] o link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["asociar un enlace"^] para configurar la conectividad entre el sistema de archivos y NetApp Console.
* Concede permisos de _vista, planificación y análisis_ en tu cuenta de AWS.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Aprende cómo conceder permisos a una cuenta de AWS"^]



Directiva sin resolver en <stdin> - include::fsx-configurations.adoc[]

.Qué sigue
link:improve-configurations-fsx.html["Implementa configuraciones bien diseñadas del sistema de archivos FSx for ONTAP"]
